language: python
python:
  - "2.7"

before_install:
  addons:
    apt:
      packages:
        - sox

install:
   - pip install -r requirements.txt

script:
  - f [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then python -m unittest discover; fi  
